version: '3'
services:
  app:
    build:
      context: .
    environment:
      POSTGRES_DATABASE: lstore-docker_development
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/l-store
      - public-data:/l-store/public
      - tmp-data:/l-store/tmp
      - log-data:/l-store/log
    depends_on:
      - db


  db:
    image: postgres:13.3
    container_name: postgresql
    ports:
      - '3306:3306'
    environment:
      POSTGRES_DATABASE: l_store_development
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/l-store/public
      - tmp-data:/l-store/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: